import csv

sequences = [
    "[FATAL] Lustre mount FAILED : bglio<*> : point <*> [INFO] CE sym <*>, at <*>, mask <*> [FATAL] Lustre mount FAILED : bglio<*> : point <*> [INFO] ciod: pollControlDescriptors: Detected the debugger died. [INFO] ciod: In packet from node <*>.<*> (<*>), message code <*> is not <*> or <*> (softheader=<*> <*> <*> <*>) [INFO] <*> torus receiver y+ input pipe error(s) (dcr <*>) detected and corrected [INFO] <*> ddr errors(s) detected and corrected on rank <*>, symbol <*>, bit <*> [INFO] CE sym <*>, at <*>, mask <*> [FATAL] ciod: Error loading <*>: invalid or missing program image, No such file or directory [FATAL] ciod: Error reading message prefix after LOAD_MESSAGE on CioStream socket to <*>:<*>: Link has been severed",
    "[INFO] generating core.<*> [INFO] generating core.<*> [FATAL] data storage interrupt [FATAL] data storage interrupt [FATAL] data storage interrupt [FATAL] data storage interrupt [FATAL] data storage interrupt [FATAL] data storage interrupt [FATAL] data storage interrupt [FATAL] data storage interrupt",
    "[INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [FATAL] rts: kernel terminated for reason <*>: bad message header: invalid cpu, type=<*>, cpu=<*>, index=<*>, total=<*>",
    "[INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [FATAL] ciod: failed to read message prefix on control stream (CioStream socket to <*>:<*> [INFO] instruction cache parity error corrected [INFO] generating core.<*> [INFO] CE sym <*>, at <*>, mask <*> [INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*>",
    "[INFO] CE sym <*>, at <*>, mask <*> [FATAL] dbcr0=<*> dbsr=<*> ccr0=<*> [FATAL] ciod: Error reading message prefix on CioStream socket to <*>:<*>, Link has been severed [INFO] ciod: Received signal <*>, code=<*>, errno=<*>, address=<*> [FATAL] ciod: Error reading message prefix on CioStream socket to <*>:<*>, Link has been severed [INFO] ciod: Received signal <*>, code=<*>, errno=<*>, address=<*> [FATAL] ciod: Error reading message prefix on CioStream socket to <*>:<*>, Link has been severed [INFO] ciod: Received signal <*>, code=<*>, errno=<*>, address=<*> [INFO] ciod: Received signal <*>, code=<*>, errno=<*>, address=<*> [FATAL] ciod: Error reading message prefix on CioStream socket to <*>:<*>, Link has been severed",
    "[INFO] CE sym <*>, at <*>, mask <*> [INFO] CE sym <*>, at <*>, mask <*> [INFO] ciod: generated <*> core files for program <*> [INFO] ciod: generated <*> core files for program <*> [FATAL] ciod: Error reading message prefix after LOAD_MESSAGE on CioStream socket to <*>:<*>: Link has been severed [INFO] data cache search parity error detected. attempting to correct [INFO] data cache search parity error detected. attempting to correct [INFO] data cache search parity error detected. attempting to correct [INFO] data cache search parity error detected. attempting to correct [INFO] data cache search parity error detected. attempting to correct",
    "[INFO] CE sym <*>, at <*>, mask <*> [INFO] total of <*> ddr error(s) detected and corrected [INFO] <*> ddr errors(s) detected and corrected on rank <*>, symbol <*>, bit <*> [INFO] CE sym <*>, at <*>, mask <*> [INFO] total of <*> ddr error(s) detected and corrected [INFO] CE sym <*>, at <*>, mask <*> [INFO] CE sym <*>, at <*>, mask <*> [INFO] CE sym <*>, at <*>, mask <*> [INFO] CE sym <*>, at <*>, mask <*> [FATAL] ciod: Error reading message prefix after LOAD_MESSAGE on CioStream socket to <*>:<*>: Link has been severed",
    "[FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt",
    "[FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt",
    "[FATAL] data storage interrupt [FATAL] data address: <*> [FATAL] data address: <*> [FATAL] data storage interrupt [FATAL] data address: <*> [FATAL] machine check: i-fetch......................<*> [FATAL] data storage interrupt [FATAL] data storage interrupt [FATAL] data storage interrupt [FATAL] data storage interrupt",
    "[INFO] iar <*> dear <*> [INFO] iar <*> dear <*> [INFO] iar <*> dear <*> [INFO] iar <*> dear <*> [INFO] iar <*> dear <*> [INFO] iar <*> dear <*> [INFO] iar <*> dear <*> [INFO] <*> floating point alignment exceptions [FATAL] Error receiving packet on tree network, expecting type <*> instead of type <*> (softheader=<*> <*> <*> <*>) PSR0=<*> PSR1=<*> PRXF=<*> PIXF=<*> [FATAL] program interrupt: privileged instruction...<*>",
    "[INFO] <*> L3 EDRAM error(s) (dcr <*>) detected and corrected [INFO] CE sym <*>, at <*>, mask <*> [INFO] CE sym <*>, at <*>, mask <*> [INFO] <*> ddr errors(s) detected and corrected on rank <*>, symbol <*>, bit <*> [INFO] CE sym <*>, at <*>, mask <*> [FATAL] rts: kernel terminated for reason <*> [INFO] iar <*> dear <*> [INFO] iar <*> dear <*> [INFO] iar <*> dear <*> [INFO] <*> floating point alignment exceptions",
    "[FATAL] instruction address: <*> [FATAL] instruction address: <*> [FATAL] instruction address: <*> [FATAL] data storage interrupt [FATAL] instruction address: <*> [FATAL] instruction address: <*> [FATAL] data address: <*> [FATAL] data address: <*> [FATAL] machine check: i-fetch......................<*> [FATAL] machine check: i-fetch......................<*>",
    "[FATAL] ciod: Error loading /<*>: invalid or missing program image, Exec format error [FATAL] ciod: Error loading /<*>: invalid or missing program image, Exec format error [FATAL] ciod: LOGIN chdir(<*>) failed: No such file or directory [FATAL] ciod: LOGIN chdir(<*>) failed: No such file or directory [FATAL] ciod: Error loading <*>: invalid or missing program image, No such file or directory [FATAL] ciod: Error reading message prefix after LOAD_MESSAGE on CioStream socket to <*>:<*>: Link has been severed [INFO] ciod: Missing or invalid fields on line <*> of node map file /<*> [FATAL] rts: kernel terminated for reason <*> [FATAL] rts: kernel terminated for reason <*> [INFO] CE sym <*>, at <*>, mask <*>",
    "[INFO] iar <*> dear <*> [INFO] <*> torus receiver z+ input pipe error(s) (dcr <*>) detected and corrected [INFO] CE sym <*>, at <*>, mask <*> [INFO] <*> L3 EDRAM error(s) (dcr <*>) detected and corrected [INFO] CE sym <*>, at <*>, mask <*> [INFO] CE sym <*>, at <*>, mask <*> [INFO] <*> ddr errors(s) detected and corrected on rank <*>, symbol <*>, bit <*> [INFO] CE sym <*>, at <*>, mask <*> [FATAL] rts: kernel terminated for reason <*> [INFO] iar <*> dear <*>",
    "[INFO] <*> tree receiver <*> in re-synch state event(s) (dcr <*>) detected [FATAL] rts: kernel terminated for reason <*> [FATAL] Error receiving packet on tree network, expecting type <*> instead of type <*> (softheader=<*> <*> <*> <*>) PSR0=<*> PSR1=<*> PRXF=<*> PIXF=<*> [INFO] CE sym <*>, at <*>, mask <*> [INFO] CE sym <*>, at <*>, mask <*> [FATAL] ciod: Error loading /<*>: invalid or missing program image, Permission denied [INFO] CE sym <*>, at <*>, mask <*> [INFO] <*> ddr errors(s) detected and corrected on rank <*>, symbol <*>, bit <*> [INFO] instruction cache parity error corrected [INFO] CE sym <*>, at <*>, mask <*>",
    "[INFO] ciod: Received signal <*>, code=<*>, errno=<*>, address=<*> [FATAL] ciod: Error reading message prefix on CioStream socket to <*>:<*>, Connection reset by peer [INFO] ciod: Received signal <*>, code=<*>, errno=<*>, address=<*> [FATAL] ciod: Error reading message prefix on CioStream socket to <*>:<*>, Connection reset by peer [FATAL] ciod: Error reading message prefix on CioStream socket to <*>:<*>, Connection timed out [FATAL] ciod: Error reading message prefix on CioStream socket to <*>:<*>, Connection reset by peer [INFO] CE sym <*>, at <*>, mask <*> [FATAL] dbcr0=<*> dbsr=<*> ccr0=<*> [FATAL] ciod: Error reading message prefix on CioStream socket to <*>:<*>, Link has been severed [INFO] ciod: Received signal <*>, code=<*>, errno=<*>, address=<*>",
    "[INFO] generating core.<*> [INFO] CE sym <*>, at <*>, mask <*> [INFO] generating core.<*> [INFO] generating core.<*> [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt",
    "[INFO] Node card VPD check: U<*> node in processor card slot J<*> do not match. VPD ecid <*>, found <*> [FATAL] rts: kernel terminated for reason <*> [FATAL] Error receiving packet on tree network, expecting type <*> instead of type <*> (softheader=<*> <*> <*> <*>) PSR0=<*> PSR1=<*> PRXF=<*> PIXF=<*> [FATAL] ciod: Error loading /<*>: invalid or missing program image, Permission denied [INFO] <*> torus sender z- retransmission error(s) (dcr <*>) detected and corrected over <*> seconds [INFO] <*> torus sender z- retransmission error(s) (dcr <*>) detected and corrected over <*> seconds [INFO] ciod: Received signal <*>, code=<*>, errno=<*>, address=<*> [INFO] ciod: Received signal <*>, code=<*>, errno=<*>, address=<*> [INFO] ciod: Received signal <*>, code=<*>, errno=<*>, address=<*> [INFO] CE sym <*>, at <*>, mask <*>",
    "[FATAL] rts panic! - stopping execution [FATAL] rts panic! - stopping execution [INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*>",
    "[FATAL] data storage interrupt [FATAL] data storage interrupt [FATAL] data storage interrupt [FATAL] data storage interrupt [FATAL] data address: <*> [FATAL] instruction address: <*> [FATAL] exception syndrome register: <*> [FATAL] exception syndrome register: <*> [FATAL] exception syndrome register: <*> [FATAL] exception syndrome register: <*>",
    "[FATAL] Error receiving packet on tree network, expecting type <*> instead of type <*> (softheader=<*> <*> <*> <*>) PSR0=<*> PSR1=<*> PRXF=<*> PIXF=<*> [INFO] critical input interrupt (unit=<*> bit=<*>): warning for torus z+ wire, suppressing further interrupts of same type [INFO] ciod: generated <*> core files for program <*> [INFO] Node card VPD check: U<*> node in processor card slot J<*> do not match. [FATAL] rts: kernel terminated for reason <*> [FATAL] Error receiving packet on tree network [FATAL] ciod: Error loading /<*>: invalid or missing program image, Permission denied",
    "[FATAL] data address: <*> [FATAL] data address: <*> [FATAL] machine check: i-fetch......................<*> [FATAL] machine check: i-fetch......................<*> [FATAL] program interrupt: illegal instruction......<*> [FATAL] data storage interrupt [FATAL] data storage interrupt [FATAL] data storage interrupt [FATAL] data storage interrupt [FATAL] data storage interrupt",
    "[FATAL] ciod: Error reading message prefix on CioStream socket to <*>:<*>, Link has been severed [FATAL] r24=<*> r25=<*> r26=<*> r27=<*> [INFO] ciod: Received signal <*>, code=<*>, errno=<*>, address=<*> [INFO] Node card VPD check: U<*> node in processor card slot J<*> do not match. [INFO] CE sym <*>, at <*>, mask <*>",
    "[INFO] CE sym <*>, at <*>, mask <*> [INFO] total of <*> ddr error(s) detected and corrected [INFO] CE sym <*>, at <*>, mask <*> [INFO] CE sym <*>, at <*>, mask <*> [FATAL] ciod: Error reading message prefix after LOAD_MESSAGE on CioStream socket to <*>:<*>: Link has been severed [INFO] ciod: generated <*> core files for program <*> [INFO] CE sym <*>, at <*>, mask <*>",
    "[INFO] instruction cache parity error corrected [INFO] instruction cache parity error corrected [INFO] instruction cache parity error corrected [INFO] <*> double-hummer alignment exceptions [INFO] CE sym <*>, at <*>, mask <*> [FATAL] ciod: failed to read message prefix on control stream (CioStream socket to <*>:<*> [FATAL] ciod: failed to read message prefix on control stream (CioStream socket to <*>:<*>",
    "[FATAL] ciod: Error loading /<*>: invalid or missing program image, Permission denied [FATAL] ciod: Error loading <*>: invalid or missing program image, No such file or directory [INFO] <*> ddr error(s) detected and corrected on rank <*>, symbol <*> over <*> seconds [FATAL] ciod: LOGIN chdir(<*>) failed: Input/output error [FATAL] ciod: Error reading message prefix on CioStream socket to <*>:<*>, Link has been severed [INFO] critical input interrupt for torus z+ wire",
    "[INFO] ciod: pollControlDescriptors: Detected the debugger died. [INFO] ciod: In packet from node <*>.<*> (<*>), message code <*> is not <*> or <*> [INFO] torus receiver y+ input pipe error(s) detected and corrected [FATAL] ciod: Error loading <*>: invalid or missing program image [FATAL] ciod: Error reading message prefix after LOAD_MESSAGE on CioStream socket",
    "[FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt",
    "[INFO] ciod: Received signal <*>, code=<*>, errno=<*>, address=<*> [FATAL] ciod: Error reading message prefix on CioStream socket to <*>:<*>, Connection timed out [FATAL] ciod: Error reading message prefix on CioStream socket to <*>:<*>, Connection reset by peer [INFO] ciod: Received signal <*>, code=<*>, errno=<*>, address=<*> [FATAL] ciod: Error reading message prefix on CioStream socket to <*>:<*>: Connection reset by peer",
    "[INFO] NFS Mount failed on bglio<*>, slept <*> seconds, retrying (<*>) [INFO] CE sym <*>, at <*>, mask <*> [INFO] <*> ddr errors(s) detected and corrected [FATAL] Lustre mount FAILED : bglio<*> : point <*> [FATAL] ciod: LOGIN chdir(<*>) failed: No such file or directory [FATAL] Lustre mount FAILED : bglio<*> : point <*>",
    "[FATAL] ciod: Error reading message prefix on CioStream socket to <*>:<*>, Link has been severed [INFO] ciod: Received signal <*>, code=<*>, errno=<*>, address=<*> [FATAL] r24=<*> r25=<*> r26=<*> r27=<*> [INFO] tree receiver <*> in re-synch state (dcr <*>) detected over <*> seconds [INFO] ciod: Received signal <*>, code=<*>, errno=<*>, address=<*>",
    "[INFO] generating core.<*> [INFO] generating core.<*> [FATAL] ciod: Error loading <*>: invalid or missing program image, No such file or directory [FATAL] rts panic! - stopping execution [INFO] generating core.<*> [INFO] generating core.<*>",
    "[INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [FATAL] ciod: failed to read message prefix on control stream (CioStream socket to <*>:<*> [INFO] instruction cache parity error corrected [INFO] generating core.<*> [INFO] CE sym <*>, at <*>, mask <*>",
    "[INFO] CE sym <*>, at <*>, mask <*> [FATAL] rts: kernel terminated for reason <*> [FATAL] Error receiving packet on tree network, expecting type <*> instead of type <*> [INFO] critical input interrupt warning for torus z+ wire [INFO] Node card VPD check mismatch detected",
    "[FATAL] data storage interrupt [FATAL] data storage interrupt [FATAL] instruction address: <*> [FATAL] instruction address: <*> [FATAL] instruction address: <*> [FATAL] instruction address: <*> [INFO] generating core.<*>",
    "[INFO] ciod: generated core files [INFO] Node card VPD mismatch [FATAL] rts: kernel terminated for reason <*> [FATAL] Error receiving packet on tree network [FATAL] ciod: Error loading /<*>: invalid or missing program image, Permission denied [INFO] torus sender retransmission error detected",
    "[FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt [FATAL] data TLB error interrupt",
    "[FATAL] ciod: Error reading message prefix after LOAD_MESSAGE on CioStream socket to <*>:<*>: Link has been severed [FATAL] Lustre mount FAILED : bglio<*> : point <*> [INFO] CE sym <*>, at <*>, mask <*> [INFO] Ido chip status changed with voltage issues [ERROR] Node card status has PGOOD and MPGOOD errors active",
    "[INFO] CE sym <*>, at <*>, mask <*> [INFO] total of ddr error(s) detected [FATAL] ciod: Error reading message prefix after LOAD_MESSAGE on CioStream socket to <*>:<*>: Link has been severed [FATAL] ciod: Error loading /<*>: invalid or missing program image, Permission denied repeated multiple times",
    "[FATAL] data TLB error interrupt [FATAL] data TLB error interrupt ... (10 times total)",
    "[FATAL] ciod: failed to read message prefix on control stream (CioStream socket to <*>:<*> [INFO] CE sym <*>, at <*>, mask <*> [INFO] generating core.<*> ... (core dumps repeated)",
    "[FATAL] data TLB error interrupt [FATAL] data TLB error interrupt ... (10 times total)",
    "[FATAL] data TLB error interrupt [FATAL] data TLB error interrupt ... (10 times total)",
    "[FATAL] data storage interrupt [FATAL] instruction address: <*> [FATAL] machine check: i-fetch......................<*> [FATAL] program interrupt: illegal instruction......<*>",
    "[INFO] ciod: generated core files [FATAL] ciod: Error reading message prefix after LOAD_MESSAGE [INFO] data cache search parity errors detected repeatedly [INFO] CE sym <*>, at <*>, mask <*>",
    "[INFO] iar <*> dear <*> [INFO] NFS Mount failed on bglio<*>, slept <*> seconds, retrying (<*>) [INFO] CE sym <*>, at <*>, mask <*> [FATAL] Lustre mount FAILED : bglio<*> : point <*>",
    "[FATAL] data storage interrupt [FATAL] data address: <*> [FATAL] machine check: i-fetch......................<*> [FATAL] exception syndrome register: <*>",
    "[FATAL] ciod: failed to read message prefix on control stream [INFO] instruction cache parity error corrected [INFO] generating core.<*> [INFO] CE sym <*>, at <*>, mask <*>",
    "[INFO] generating core.<*> [INFO] generating core.<*> [INFO] generating core.<*> [FATAL] ciod: Error loading <*>: invalid or missing program image [FATAL] ciod: Error creating node map from file <*>: No child processes",
    "[FATAL] ciod: Error reading message prefix after LOAD_MESSAGE... [FATAL] ciod: Error loading /<*>: invalid or missing program image, Permission denied (twice)",
    "[FATAL] data TLB error interrupt (repeated 10 times)",
    "[FATAL] ciod: Error reading message prefix after LOAD_MESSAGE... [INFO] CE sym <*>, at <*>, mask <*> [FATAL] ciod: Error loading /<*>: invalid or missing program image, Permission denied",
    "[FATAL] instruction address: <*> [INFO] generating core.<*> (multiple times) [FATAL] data storage interrupt (twice)",
    "[FATAL] Lustre mount FAILED : bglio<*> : point <*> (several times) [INFO] CE sym <*>, at <*>, mask <*> [INFO] Torus input pipe error detected and corrected",
    "[INFO] ciod: Received signal <*>, address=<*> [FATAL] Lustre mount FAILED : bglio<*> [INFO] MACHINE CHECK DCR read timeout",
    "[FATAL] data TLB error interrupt (repeated 10 times)",
    "[FATAL] ciod: Error loading /<*>: invalid or missing program image, Exec format error (many times) [FATAL] ciod: LOGIN chdir(<*>) failed: No such file or directory",
    "[INFO] CE sym <*>, at <*>, mask <*> (multiple times) [FATAL] ciod: Error reading message prefix after LOAD_MESSAGE [INFO] critical input interrupt for torus y+ wire",
    "[INFO] ciod: Missing or invalid fields on node map file [FATAL] rts: kernel terminated for reason <*> [FATAL] ciod: LOGIN chdir(<*>) failed: No such file or directory [INFO] core files generated",
    "[FATAL] Lustre mount FAILED, multiple MACHINE CHECK DCR read timeouts, repeated system signals",
    "[INFO] iar <*> dear <*> logs, floating point alignment exceptions, fatal tree network packet mismatch, privileged instruction program interrupt",
    "[FATAL] Error loading program image (Permission denied), retransmission errors, multiple received signals, Lustre mount failure",
    "[FATAL] Severed CioStream link, repeated failed program image loads, CE correctable memory errors, interrupt suppressions",
    "[INFO] multiple core generations, [FATAL] kernel terminated with bad message header, floating point alignment exceptions",
    "[FATAL] Data TLB error interrupts mixed with CE memory errors, message code mismatches, fatal data storage interrupts",
    "[FATAL] Heavy repeated data TLB error interrupts (10 times)",
    "[INFO] generating many core files, [FATAL] failed to read message prefix on control stream (communication failure)",
    "[INFO] MACHINE CHECK DCR read timeouts, multiple system signals received, [FATAL] CioStream socket timeouts and connection resets",
    "[INFO] Corrected DDR memory errors, [FATAL] program loading failure, critical input interrupt warnings, tree network resyncs, kernel termination, packet errors, CE errors",
    "[FATAL] data TLB error interrupt (repeated 10 times)",
    "[FATAL] Lustre mount failures, node card VPD mismatches, torus input errors, login chdir failures, CE errors",
    "[INFO] Corrected DDR memory errors, [FATAL] kernel terminated, iar/dear logs, floating point alignment exceptions, core file generations",
    "[INFO] Repeated MACHINE CHECK DCR read timeouts, system signals, [FATAL] CioStream connection resets and timeouts",
    "[FATAL] data TLB error interrupt (repeated 10 times)",
    "[INFO] Core file generations, [INFO] CE correctable errors, [FATAL] data TLB errors and repeated TLB faults",
    "[INFO] Floating point alignment exceptions, core files generated, DDR memory corrections, [FATAL] kernel termination, tree network packet errors",
    "[FATAL] Login directory failures, invalid or missing program image errors, communication severed after LOAD_MESSAGE, invalid node map fields",
    "[INFO] Suppressed interrupts, corrected DDR memory errors, tree network resyncs, core file generations, [FATAL] communication severed after LOAD_MESSAGE, data cache parity errors",
    "[FATAL] multiple data storage interrupts, instruction address faults (overwriting memory or CPU failure)",
    "[INFO] CE sym mask corrections, [INFO] DDR memory corrections, [FATAL] minus normalized/fraction rounded errors, Lustre mount failures",
    "[FATAL] multiple data storage interrupts and many instruction address faults, followed by storage interrupts again",
    "[FATAL] data TLB error interrupts (10 times repeated)",
    "[INFO] CE sym corrections, [FATAL] invalid/missing program image load errors, severed message links, memory corrections, DDR error recoveries",
    "[FATAL] repeated data TLB faults mixed with message code mismatches and data storage interrupts",
    "[INFO] Node VPD mismatches, torus receiver errors, [FATAL] Lustre mount failures, login chdir failures, CE memory errors, debugger crashes",
    "[INFO] instruction cache parity corrections, [INFO] double-hummer alignment exceptions, [FATAL] failed control stream reads, CE errors, core generations",
    "[INFO] core file generations, [FATAL] repeated TLB faults (memory address translations failing)",
    "[INFO] generating core files, [FATAL] program load failures, RTS panic termination, indicating total system crash",
    "[FATAL] severed communication links, corrected DDR errors, invalid/missing program images, critical input interrupts, debugger died",
    "[INFO] DDR corrections, [FATAL] minus normalized errors, Lustre mount failures, scratchpad size warnings, integer alignment exceptions",
    "[FATAL] invalid program image loads, core file generations, memory corrections, tree receiver resyncs, kernel terminations, network packet failures",
    "[FATAL] multiple Lustre mount failures, login directory failures, node card VPD mismatches, torus receiver input errors",
    "[FATAL] repeated program image permission denied errors, severed communication links, CE memory corrections",
    "[FATAL] kernel termination due to bad message header, debug wait hangs, floating point alignment exceptions, core dumps",
    "[INFO] core files generated, [FATAL] Lustre mount failures, login chdir failures, memory corrections, node card mismatches",
    "[FATAL] repeated communication severing after LOAD_MESSAGE, Lustre mount failures, Ido chip status changes, power supply errors detected",
    "[FATAL] repeated data storage interrupts mixed with invalid instruction addresses and faulty memory accesses",
]

reasons = [
    "Storage mount failures, debugger crashes, and communication errors indicate severe system instability and possible hardware faults.",
    "Repeated fatal data storage interrupts suggest a critical failure in the storage subsystem, preventing normal operations.",
    "Multiple core generations followed by a kernel termination due to bad message headers point to fatal communication or CPU assignment issues.",
    "Core dumps combined with communication failures and instruction cache errors highlight memory corruption and network instability.",
    "Severe repeated disconnections and hardware register faults indicate node communication breakdown and potential hardware damage.",
    "Multiple data cache parity errors and severed communication links show critical memory subsystem issues and system instability.",
    "Frequent correctable memory errors along with network disconnections suggest worsening hardware degradation and unstable operations.",
    "Continuous fatal data TLB error interrupts indicate a major memory address translation failure, impacting system reliability.",
    "Persistent data TLB errors across multiple logs confirm a critical fault in memory management hardware.",
    "Data storage interrupts, invalid memory addresses, and machine check errors indicate catastrophic memory and CPU subsystem failures.",
    "Floating point exceptions and network packet errors indicate serious data transmission and computation faults.",
    "Memory and cache correctable errors combined with kernel termination suggest underlying hardware failures escalating to critical crashes.",
    "Frequent invalid instruction and data address faults, along with machine check errors, imply catastrophic CPU or memory corruption.",
    "Filesystem and job loader errors indicate missing binaries, filesystem corruption, and widespread system loading failures.",
    "Memory, cache, and network errors show a high risk of node failure due to degraded hardware reliability.",
    "Tree network synchronization issues and packet mismatches suggest serious inter-node communication failures and hardware faults.",
    "Severe network disconnections, timed-out socket errors, and hardware faults are destabilizing node communications and operations.",
    "Frequent TLB errors and memory corruption point to major address translation failures, critically affecting system stability.",
    "Hardware VPD mismatches and repeated communication packet failures point to hardware configuration or physical installation problems.",
    "RTS panic and mass core file generation point to total system crash caused by fatal, unrecoverable internal errors.",
    "Multiple data storage and exception register errors indicate memory corruption and processor faults causing system instability.",
    "Repeated network packet failures, node mismatches, and program load issues suggest hardware wiring faults and filesystem corruption.",
    "Frequent memory and instruction fetch errors signal severe CPU or memory faults, causing illegal instruction execution.",
    "Link severing, register dumps, and repeated hardware mismatch errors suggest physical node damage or severe communication errors.",
    "Corrected DDR memory errors and link failures point to escalating memory hardware failures despite error correction attempts.",
    "Persistent instruction cache parity and alignment errors indicate severe memory and CPU cache corruption impacting system reliability.",
    "Filesystem and memory loading failures combined with critical interrupts show both I/O subsystem corruption and hardware instability.",
    "Debugger crashes, corrupted packets, and missing program loads indicate deep communication, memory, and application layer instability.",
    "Massive data TLB fault spamming indicates a major page table or address translation failure, crippling system memory operations.",
    "Severe connection resets, timeouts, and communication failures suggest network or interconnect hardware breakdown.",
    "Multiple storage mount failures and login errors indicate severe filesystem access problems and node instability.",
    "Repeated severed links, hardware register dumps, and network re-synchronization issues suggest communication subsystem failures.",
    "Core file generations and program loading failures followed by system panic indicate widespread memory and filesystem corruption.",
    "Communication failures and cache errors combined with frequent core dumps indicate serious CPU or memory subsystem degradation.",
    "Kernel termination, network packet errors, and node hardware mismatches suggest critical node hardware communication failures.",
    "Frequent instruction address and data storage faults indicate catastrophic memory corruption and CPU fetch failures.",
    "Node mismatch, retransmission errors, and program loading failures signal critical system hardware and filesystem corruption.",
    "Massive repeated data TLB faults show complete memory management and page translation subsystem breakdown.",
    "Severed communication links, failed Lustre mounts, and voltage errors point to power and storage subsystem instability.",
    "Massive filesystem loading failures, memory errors, and program loading errors indicate node and storage subsystem collapse.",
    "Massive repeated TLB errors indicate complete breakdown of memory address translation subsystem, critically affecting system operation.",
    "Failed control stream message reads combined with core dumps suggest network instability and repeated system crashes.",
    "Heavy data TLB error spamming reflects systemic memory access issues causing major operational failures.",
    "Continuous TLB faults point to critical failure in memory management hardware, severely disrupting node stability.",
    "Illegal instruction fetches, invalid addresses, and machine checks indicate severe processor and memory faults leading to fatal interruptions.",
    "Core dumps combined with severed communication links and repeated cache parity errors show critical system memory and communication degradation.",
    "Frequent NFS mount failures, memory errors, and repeated core dumps point to mounting, storage, and memory subsystem instability.",
    "Frequent storage and memory address failures along with illegal instructions indicate catastrophic hardware and software corruption.",
    "Failed control stream reads, repeated core dumps, and memory parity corrections highlight major CPU-memory interconnect faults.",
    "Core dumps, missing program images, and node map failures indicate file system corruption and severe job launch failures.",
    "Repeated link severing and program load failures point to filesystem corruption and severe communication faults.",
    "Massive repeated data TLB faults indicate total failure of address translation and memory management subsystem.",
    "Severed communication links, missing program images, and critical input errors indicate escalating node and storage instability.",
    "Instruction address faults and repeated data storage failures reveal critical CPU and memory corruption.",
    "Frequent Lustre mount failures combined with network and memory errors show widespread storage and communication system breakdown.",
    "Repeated system signals, Lustre failures, and machine check timeouts point to deep hardware failures affecting CPU and memory.",
    "Heavy data TLB error flooding suggests severe breakdown of virtual memory and memory access paths.",
    "Repeated program load failures, missing files, and chdir login failures signal severe filesystem and node management failure.",
    "Link severing, critical interrupts, and cache errors show critical instability in node hardware and memory interconnects.",
    "Invalid node map fields, kernel panics, and login errors indicate deep system configuration corruption and job scheduler instability.",
    "Repeated Lustre mount failures and continuous machine check timeouts point to critical hardware instability and memory access faults.",
    "Floating point exceptions, tree network packet mismatches, and privileged instruction failures indicate computation and interconnect corruption.",
    "Permission denied errors when loading programs, combined with network retransmission faults and Lustre failures, point to storage and communication breakdown.",
    "Severed communication links and repeated program loading failures indicate deep filesystem corruption and critical network instability.",
    "Multiple core dumps, floating point errors, and fatal header parsing issues show widespread memory corruption and CPU communication failure.",
    "Mixed memory correctable errors, message protocol mismatches, and fatal TLB faults indicate escalating node instability and memory corruption.",
    "Massive repeated TLB errors show complete memory address translation collapse, making the node unable to continue operations.",
    "Mass core dumps with communication failures during control stream operations show fatal system communication and scheduling breakdown.",
    "Continuous machine check faults, severed communication links, and repeated connection resets suggest critical hardware and memory controller failure.",
    "Repeated DDR memory corrections, filesystem loading failures, packet errors, and kernel terminations indicate serious node instability and hardware degradation.",
    "Heavy repeated TLB errors indicate severe breakdown in memory address translation, crippling node functionality.",
    "Frequent Lustre mount failures, node card mismatches, and login errors suggest severe storage system and hardware mapping failures.",
    "Mixed DDR memory corrections, floating point alignment faults, and kernel termination show node instability and memory corruption.",
    "Continuous machine check timeouts and severed communication links point to critical CPU and memory controller failures.",
    "Persistent massive TLB errors indicate collapse of memory page management systems, halting node operations.",
    "Continuous core dumps with frequent CE memory errors and TLB faults highlight severe CPU and memory faults causing node crashes.",
    "Floating point errors, tree network packet failures, and critical interrupts suggest communication and memory subsystem degradation.",
    "Repeated login failures, missing program images, node map corruption, and severed links point to filesystem and communication system collapse.",
    "DDR memory corrections, core dumps, tree receiver resyncs, and parity cache errors point to escalating node hardware degradation and instability.",
    "Massive storage interrupts and instruction address faults point to major memory corruption and CPU instruction fetch failures.",
    "Memory errors and storage system failures along with Lustre mount problems suggest critical filesystem corruption and data handling faults.",
    "Repeated storage interrupts and invalid instruction address accesses indicate full collapse of node memory and CPU stability.",
    "Continuous TLB error interrupts signal total breakdown of address translation hardware in the memory subsystem.",
    "Filesystem loading errors, severed links, and repeated memory corrections reveal severe node instability and communication subsystem failures.",
    "Heavy data TLB errors combined with message mismatches and storage faults suggest escalating memory and protocol corruption.",
    "Hardware VPD mismatches, network input errors, and Lustre mount problems indicate severe hardware misconfiguration and storage faults.",
    "Instruction cache parity errors, double-hummer alignment faults, and control stream failures show deep CPU and cache corruption issues.",
    "Frequent core file generations combined with massive repeated TLB faults indicate catastrophic failure of memory management systems.",
    "Program load errors and RTS panic stop conditions show total kernel instability and unrecoverable system crashes.",
    "Severed communication, program loading failures, critical interrupts, and repeated DDR error corrections indicate node instability and hardware failures.",
    "Memory errors, storage mount failures, alignment exceptions, and system warnings highlight widespread hardware degradation and configuration faults.",
    "Filesystem load failures, memory corruption, kernel panics, and packet errors point to system-wide communication and storage subsystem collapse.",
    "Frequent Lustre mount failures and node card VPD mismatches indicate severe hardware mapping and storage access failures.",
    "Program load failures combined with severed communication links and memory faults suggest critical filesystem and network communication breakdown.",
    "Bad message headers, debug waits, and alignment errors leading to core dumps show CPU communication breakdown and kernel-level crashes.",
    "Mass Lustre mount failures, login failures, and node hardware mismatches indicate system storage and interconnect corruption.",
    "Repeated severed links, hardware status faults, and power instability show deep hardware degradation affecting core system operations.",
    "Frequent storage faults, invalid memory accesses, and instruction fetch failures signal major CPU and memory corruption leading to fatal node crashes.",
]


output_file = "./data/anomaly_explantion.csv"

with open(output_file, mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["sequence", "reason"])

    for seq, reason in zip(sequences, reasons):
        writer.writerow([seq, reason])

print(f"Created a dataset with {len(sequences)} sequences & {len(reasons)} of their reasons, & stored in '{output_file}'")
