name: Build & Push to ECR

on:
    push:
        branches: [main]

env:
    AWS_REGION: us-east-1
    ECR_REPOSITORY: fine-tuned-anomaly-detection

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Login to ECR
              run: |
                  aws ecr get-login-password --region $AWS_REGION \
                    | docker login --username AWS --password-stdin \
                      586964278361.dkr.ecr.$AWS_REGION.amazonaws.com

            - name: Build and push
              run: |
                  SHORT_SHA=${GITHUB_SHA::7}
                  IMAGE=586964278361.dkr.ecr.$AWS_REGION.amazonaws.com/fine-tuned-anomaly-detection:$SHORT_SHA
                  docker build -t $IMAGE .
                  docker push $IMAGE
